name: service_tracker
description: A Flutter app to track car services and maintenance
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.3
  csv: ^6.0.0
  webdav_client: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/app_icon.png
    - assets/car-logos/brands.json
    - assets/car-logos/

